openapi: 3.0.3
info:
  title: Notifications API
  description: |
    Notification management and preferences API.

    Features:
    - View notification history
    - Manage notification preferences
    - Mark notifications as read
    - Subscribe/unsubscribe from notification channels
  version: 1.0.0
  contact:
    name: Platform Team

servers:
  - url: '{baseUrl}/api/v1'
    variables:
      baseUrl:
        default: https://api.example.com
        description: Base API URL

tags:
  - name: Notifications
    description: Notification operations
  - name: Preferences
    description: Notification preferences
  - name: Subscriptions
    description: Channel subscriptions

security:
  - bearerAuth: []

paths:
  /notifications:
    get:
      operationId: listNotifications
      summary: List notifications
      description: Get paginated list of notifications for the current user
      tags:
        - Notifications
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/PageSizeParam'
        - name: status
          in: query
          schema:
            type: string
            enum: [unread, read, all]
            default: all
          description: Filter by read status
        - name: category
          in: query
          schema:
            type: string
          description: Filter by category
        - name: type
          in: query
          schema:
            type: string
            enum: [email, sms, push, in_app]
          description: Filter by notification type
        - name: since
          in: query
          schema:
            type: string
            format: date-time
          description: Get notifications since this time
      responses:
        '200':
          description: Notification list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /notifications/unread-count:
    get:
      operationId: getUnreadCount
      summary: Get unread notification count
      description: Get count of unread notifications
      tags:
        - Notifications
      responses:
        '200':
          description: Unread count
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  by_category:
                    type: object
                    additionalProperties:
                      type: integer
        '401':
          $ref: '#/components/responses/Unauthorized'

  /notifications/{notificationId}:
    parameters:
      - $ref: '#/components/parameters/NotificationIdParam'

    get:
      operationId: getNotification
      summary: Get notification details
      description: Get a specific notification
      tags:
        - Notifications
      responses:
        '200':
          description: Notification details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      operationId: deleteNotification
      summary: Delete notification
      description: Delete a notification from history
      tags:
        - Notifications
      responses:
        '204':
          description: Notification deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /notifications/{notificationId}/read:
    parameters:
      - $ref: '#/components/parameters/NotificationIdParam'

    post:
      operationId: markAsRead
      summary: Mark notification as read
      description: Mark a specific notification as read
      tags:
        - Notifications
      responses:
        '200':
          description: Notification marked as read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /notifications/read-all:
    post:
      operationId: markAllAsRead
      summary: Mark all notifications as read
      description: Mark all notifications as read for the current user
      tags:
        - Notifications
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Only mark notifications in this category
                before:
                  type: string
                  format: date-time
                  description: Only mark notifications before this time
      responses:
        '200':
          description: Notifications marked as read
          content:
            application/json:
              schema:
                type: object
                properties:
                  updated_count:
                    type: integer
        '401':
          $ref: '#/components/responses/Unauthorized'

  /notifications/preferences:
    get:
      operationId: getNotificationPreferences
      summary: Get notification preferences
      description: Get the current user's notification preferences
      tags:
        - Preferences
      responses:
        '200':
          description: Notification preferences
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationPreferences'
        '401':
          $ref: '#/components/responses/Unauthorized'

    put:
      operationId: updateNotificationPreferences
      summary: Update notification preferences
      description: Update the current user's notification preferences
      tags:
        - Preferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNotificationPreferencesRequest'
      responses:
        '200':
          description: Preferences updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationPreferences'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /notifications/categories:
    get:
      operationId: listNotificationCategories
      summary: List notification categories
      description: Get available notification categories and their settings
      tags:
        - Preferences
      responses:
        '200':
          description: Notification categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/NotificationCategory'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /notifications/subscriptions:
    get:
      operationId: listSubscriptions
      summary: List channel subscriptions
      description: Get user's notification channel subscriptions
      tags:
        - Subscriptions
      responses:
        '200':
          description: Subscription list
          content:
            application/json:
              schema:
                type: object
                properties:
                  subscriptions:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChannelSubscription'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      operationId: subscribe
      summary: Subscribe to channel
      description: Subscribe to a notification channel
      tags:
        - Subscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscribeRequest'
      responses:
        '201':
          description: Subscribed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelSubscription'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /notifications/subscriptions/{subscriptionId}:
    parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          type: string
          format: uuid

    delete:
      operationId: unsubscribe
      summary: Unsubscribe from channel
      description: Unsubscribe from a notification channel
      tags:
        - Subscriptions
      responses:
        '204':
          description: Unsubscribed successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /notifications/devices:
    get:
      operationId: listDevices
      summary: List registered devices
      description: Get list of devices registered for push notifications
      tags:
        - Subscriptions
      responses:
        '200':
          description: Device list
          content:
            application/json:
              schema:
                type: object
                properties:
                  devices:
                    type: array
                    items:
                      $ref: '#/components/schemas/RegisteredDevice'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      operationId: registerDevice
      summary: Register device for push
      description: Register a device for push notifications
      tags:
        - Subscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDeviceRequest'
      responses:
        '201':
          description: Device registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisteredDevice'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /notifications/devices/{deviceId}:
    parameters:
      - name: deviceId
        in: path
        required: true
        schema:
          type: string
          format: uuid

    delete:
      operationId: unregisterDevice
      summary: Unregister device
      description: Remove a device from push notification registration
      tags:
        - Subscriptions
      responses:
        '204':
          description: Device unregistered
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /notifications/test:
    post:
      operationId: sendTestNotification
      summary: Send test notification
      description: Send a test notification to the current user
      tags:
        - Notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - channel
              properties:
                channel:
                  type: string
                  enum: [email, sms, push]
                message:
                  type: string
                  description: Custom test message
      responses:
        '200':
          description: Test notification sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  notification_id:
                    type: string
                    format: uuid
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    NotificationIdParam:
      name: notificationId
      in: path
      required: true
      schema:
        type: string
        format: uuid

    PageParam:
      name: page
      in: query
      schema:
        type: integer
        minimum: 1
        default: 1

    PageSizeParam:
      name: page_size
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Notification:
      type: object
      required:
        - id
        - type
        - category
        - title
        - created_at
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [email, sms, push, in_app]
        category:
          type: string
        title:
          type: string
        body:
          type: string
        data:
          type: object
          additionalProperties: true
        action_url:
          type: string
          format: uri
        image_url:
          type: string
          format: uri
        read:
          type: boolean
          default: false
        read_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time

    NotificationListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
        pagination:
          $ref: '#/components/schemas/Pagination'

    Pagination:
      type: object
      properties:
        page:
          type: integer
        page_size:
          type: integer
        total_items:
          type: integer
        total_pages:
          type: integer
        has_next:
          type: boolean
        has_previous:
          type: boolean

    NotificationPreferences:
      type: object
      properties:
        email_enabled:
          type: boolean
        sms_enabled:
          type: boolean
        push_enabled:
          type: boolean
        in_app_enabled:
          type: boolean
        digest_frequency:
          type: string
          enum: [realtime, hourly, daily, weekly, never]
        digest_time:
          type: string
          pattern: '^([01]?[0-9]|2[0-3]):[0-5][0-9]$'
        quiet_hours:
          type: object
          properties:
            enabled:
              type: boolean
            start:
              type: string
            end:
              type: string
            timezone:
              type: string
        categories:
          type: object
          additionalProperties:
            type: object
            properties:
              email:
                type: boolean
              sms:
                type: boolean
              push:
                type: boolean
              in_app:
                type: boolean

    UpdateNotificationPreferencesRequest:
      type: object
      properties:
        email_enabled:
          type: boolean
        sms_enabled:
          type: boolean
        push_enabled:
          type: boolean
        in_app_enabled:
          type: boolean
        digest_frequency:
          type: string
          enum: [realtime, hourly, daily, weekly, never]
        digest_time:
          type: string
        quiet_hours:
          type: object
          properties:
            enabled:
              type: boolean
            start:
              type: string
            end:
              type: string
            timezone:
              type: string
        categories:
          type: object
          additionalProperties:
            type: object
            properties:
              email:
                type: boolean
              sms:
                type: boolean
              push:
                type: boolean
              in_app:
                type: boolean

    NotificationCategory:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        default_channels:
          type: array
          items:
            type: string
            enum: [email, sms, push, in_app]
        required:
          type: boolean
          description: Whether this category cannot be disabled
        configurable:
          type: boolean
          description: Whether user can configure channels

    ChannelSubscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
        channel:
          type: string
        topic:
          type: string
        subscribed_at:
          type: string
          format: date-time

    SubscribeRequest:
      type: object
      required:
        - channel
        - topic
      properties:
        channel:
          type: string
          enum: [email, push, webhook]
        topic:
          type: string
        endpoint:
          type: string
          format: uri
          description: Webhook endpoint (for webhook channel)

    RegisteredDevice:
      type: object
      properties:
        id:
          type: string
          format: uuid
        platform:
          type: string
          enum: [ios, android, web]
        name:
          type: string
        model:
          type: string
        last_active_at:
          type: string
          format: date-time
        registered_at:
          type: string
          format: date-time

    RegisterDeviceRequest:
      type: object
      required:
        - token
        - platform
      properties:
        token:
          type: string
          description: Push notification token
        platform:
          type: string
          enum: [ios, android, web]
        name:
          type: string
          description: Device name
        model:
          type: string
          description: Device model
        app_version:
          type: string
          description: App version

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
