openapi: 3.0.3
info:
  title: Webhooks Service API
  description: API for webhook management and delivery
  version: 1.0.0

paths:
  /webhooks:
    get:
      summary: List webhooks
      operationId: listWebhooks
      tags:
        - Webhooks
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: page_size
          in: query
          schema:
            type: integer
            default: 20
        - name: is_active
          in: query
          schema:
            type: boolean
        - name: event
          in: query
          schema:
            type: string
          description: Filter by subscribed event
      responses:
        '200':
          description: List of webhooks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookListResponse'

    post:
      summary: Create webhook
      operationId: createWebhook
      tags:
        - Webhooks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWebhookRequest'
      responses:
        '201':
          description: Webhook created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
        '400':
          description: Invalid request

  /webhooks/{webhook_id}:
    get:
      summary: Get webhook
      operationId: getWebhook
      tags:
        - Webhooks
      parameters:
        - name: webhook_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Webhook details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
        '404':
          description: Webhook not found

    put:
      summary: Update webhook
      operationId: updateWebhook
      tags:
        - Webhooks
      parameters:
        - name: webhook_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWebhookRequest'
      responses:
        '200':
          description: Webhook updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
        '404':
          description: Webhook not found

    delete:
      summary: Delete webhook
      operationId: deleteWebhook
      tags:
        - Webhooks
      parameters:
        - name: webhook_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Webhook deleted
        '404':
          description: Webhook not found

  /webhooks/{webhook_id}/test:
    post:
      summary: Test webhook
      description: Send a test payload to the webhook endpoint
      operationId: testWebhook
      tags:
        - Webhooks
      parameters:
        - name: webhook_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                event:
                  type: string
                  description: Event type to simulate
      responses:
        '200':
          description: Test result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookTestResult'
        '404':
          description: Webhook not found

  /webhooks/{webhook_id}/rotate-secret:
    post:
      summary: Rotate webhook secret
      description: Generate a new signing secret for the webhook
      operationId: rotateWebhookSecret
      tags:
        - Webhooks
      parameters:
        - name: webhook_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Secret rotated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
        '404':
          description: Webhook not found

  /webhooks/{webhook_id}/deliveries:
    get:
      summary: List webhook deliveries
      operationId: listDeliveries
      tags:
        - Deliveries
      parameters:
        - name: webhook_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: page_size
          in: query
          schema:
            type: integer
            default: 20
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, success, failed, retrying]
        - name: event
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of deliveries
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryListResponse'
        '404':
          description: Webhook not found

  /webhooks/{webhook_id}/deliveries/{delivery_id}:
    get:
      summary: Get delivery details
      operationId: getDelivery
      tags:
        - Deliveries
      parameters:
        - name: webhook_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: delivery_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Delivery details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookDelivery'
        '404':
          description: Delivery not found

  /webhooks/{webhook_id}/deliveries/{delivery_id}/retry:
    post:
      summary: Retry failed delivery
      operationId: retryDelivery
      tags:
        - Deliveries
      parameters:
        - name: webhook_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: delivery_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Retry initiated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookDelivery'
        '400':
          description: Cannot retry (not failed)
        '404':
          description: Delivery not found

  /webhooks/events:
    get:
      summary: List available events
      description: Get list of all webhook events that can be subscribed to
      operationId: listEvents
      tags:
        - Events
      responses:
        '200':
          description: Available events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventListResponse'

components:
  schemas:
    WebhookEvent:
      type: string
      enum:
        - user.created
        - user.updated
        - user.deleted
        - user.activated
        - user.deactivated
        - team.created
        - team.updated
        - team.deleted
        - team.member_added
        - team.member_removed
        - team.member_role_changed
        - invitation.created
        - invitation.sent
        - invitation.accepted
        - invitation.expired
        - invitation.revoked
        - role.created
        - role.updated
        - role.deleted
        - role.assigned
        - role.removed
        - session.created
        - session.expired
        - settings.updated

    Webhook:
      type: object
      properties:
        id:
          type: string
          format: uuid
        tenant_id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        url:
          type: string
          format: uri
        secret:
          type: string
        events:
          type: array
          items:
            $ref: '#/components/schemas/WebhookEvent'
        headers:
          type: object
          additionalProperties:
            type: string
        is_active:
          type: boolean
        retry_count:
          type: integer
        timeout_seconds:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    WebhookDelivery:
      type: object
      properties:
        id:
          type: string
          format: uuid
        webhook_id:
          type: string
          format: uuid
        event:
          $ref: '#/components/schemas/WebhookEvent'
        payload:
          type: object
        request_headers:
          type: object
          additionalProperties:
            type: string
        response_status:
          type: integer
        response_headers:
          type: object
          additionalProperties:
            type: string
        response_body:
          type: string
        duration_ms:
          type: integer
        attempts:
          type: integer
        status:
          type: string
          enum: [pending, success, failed, retrying]
        error_message:
          type: string
        next_retry_at:
          type: string
          format: date-time
        delivered_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time

    CreateWebhookRequest:
      type: object
      required:
        - name
        - url
        - events
      properties:
        name:
          type: string
          maxLength: 100
        description:
          type: string
          maxLength: 500
        url:
          type: string
          format: uri
        events:
          type: array
          items:
            $ref: '#/components/schemas/WebhookEvent'
          minItems: 1
        headers:
          type: object
          additionalProperties:
            type: string
        retry_count:
          type: integer
          default: 3
        timeout_seconds:
          type: integer
          default: 30

    UpdateWebhookRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        url:
          type: string
          format: uri
        events:
          type: array
          items:
            $ref: '#/components/schemas/WebhookEvent'
        headers:
          type: object
          additionalProperties:
            type: string
        is_active:
          type: boolean
        retry_count:
          type: integer
        timeout_seconds:
          type: integer

    WebhookTestResult:
      type: object
      properties:
        success:
          type: boolean
        status_code:
          type: integer
        duration_ms:
          type: integer
        error:
          type: string

    WebhookListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Webhook'
        total:
          type: integer
        page:
          type: integer
        page_size:
          type: integer

    DeliveryListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/WebhookDelivery'
        total:
          type: integer
        page:
          type: integer
        page_size:
          type: integer

    EventListResponse:
      type: object
      properties:
        events:
          type: array
          items:
            type: object
            properties:
              name:
                $ref: '#/components/schemas/WebhookEvent'
              description:
                type: string
              category:
                type: string
